tunnels:
  supabase:
    commandLine: tuna http  http://kong:8000 --subdomain=docker-supabase
    tags: [frontend, supabase]
  minio:
    commandLine: tuna http  http://minio:9000 --subdomain=docker-minio
    tags: [frontend, minio]
  postgres:
    commandLine: tuna tcp 5432 --port=postgres
    tags: [backend, postgres]
  minio-api:
    commandLine: tuna http  http://minio:9001 --subdomain=docker-minio-api
    tags: [backend, minio , s3]